service: myService

provider:
    name: aws
    runtime: nodejs12.x

functions:
  app:
    handler: handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
        cors: true

plugins:
  - serverless-offline