service: myService

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
    
inputs:
  src:
    src: ./src
    hook: yarn build
    dist: ./build

functions:
  app:
    handler: handler.handler
    events:
      - http: ANY /
        cors: true
      - http: 'ANY {proxy+}'
        cors: true

plugins:
  - serverless-offline
  - serverless-aws-static-file-handler