
service: tpt-serverless-test

provider:
  name: aws
  runtime: nodejs12.x

functions:
  app:
    handler: handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

package:
  exclude:
    - client/**
    - '!client/build/**'

plugins:
  - serverless-offline